# Generated by Django 4.2.16 on 2024-09-30 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdn_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('category', models.CharField(choices=[('blocked_rule', 'Blocked Rule'), ('redirected_rule', 'Redirected Rule')], default='blocked_rule', max_length=30)),
                ('rule_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_rule', to='sdn_app.server')),
            ],
        ),
    ]
